
# Site settings
title: Dylan Flesch
email: dylanflesch@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Libraries, Archives, Music and Radio.
url: "dylanflesch.org"

# baseurl: "/website" # the subpath of your site, e.g. /blog
# url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dylanflesch
github_username:  dylanflesch

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed

exclude:

   - Gemfile
   - Gemfile.lock

# Google Analytics
google_analytics: UA-176805256-1
